### ISSUE TITLE
[Feature] Configure testing environment

### ISSUE THREAD

**Issue by byliuyang** [short-d/short#406]
**What is the problem?**
Currently, developers don't have their own sandboxed environment to verify their feature is working properly with the underlying infrastructure.

**Your solution**
Configure testing environment and automatically deploy PR branch ending with `*-testing`. Delete the environment when the branch is deleted.

**Alternatives considered**
Launch Kubernete cluster on local machine. This involves extensive configurations and complex setup. It's forces each new team members to spend weeks to months to learn Kubernetes in order to configure their local environment.

**Comment by nathan815** [comment]
> Configure testing environment and automatically deploy PR branch ending with *-testing.

I think this could lead to a lot of branches being named in the format `*-testing`, as many developers will probably want to be able to test their changes in a testing environment. It's also great for enabling reviewers to quickly test the changes as well. Maybe it should just create a testing environment instance for every PR?

**Comment by byliuyang** [comment]
@nathan815 Good catch! Ideally what you suggested is what I have been looking for due to great developer convenience. However, there are two challenges need to addressed, which temporarily dragged me to a `*-testing` branch approach :

1) Creating environment for every branch need to dynamically create and delete namespaces on Kurbernetes. This can't simply use simple static configs, which is very complex to do. You can try it out, if succeed, then awesome job!

2) There are limited resources on the server. The more environments the server have, the slower our production service is. I currently don't have money to cover extra server cost.

Maybe it shouldn't be `*-testing` branch. It should be `testing` instead to prevent concurrent deployment issue. Setting up environment on local machine should be fairly simple.

**Comment by rohithbalaji123** [comment]
Yeah, having a single branch named `testing` sounds good. It prevents both concurrent deployment issues and also using huge resources from the server if not maintained properly.

The non technical part of this feature would involve,
- Allow force pushing in this branch to allow multiple developers test while the previous changes in the branch are not merged.
- Have a slack channel dedicated to this branch where people can post message stating, "Bouncing `testing` in 10 minutes", so that the previous tester would be aware that the branch is going to be overwritten in the next 10 mins. The previous tester can ignore the message if tests are already done or ask the new tester to wait for few more minutes to allow him to complete his tests.

Thought? @byliuyang

**Comment by byliuyang** [comment]
@rohithbalaji123 Great interpretation! This branch will allow force push. I am thinking in the future, we can have a resource allocation system where people can book testing branch for certain period for their demo sessions ahead of time.

Ideally we want to span up testing environment for every PR in the future so that there won't be any usage conflicts.

**Comment by rohithbalaji123** [comment]
User flow:
- A developer pushes changes to the testing branch.
- CI starts running and push a docker image to Dockerhub
- Dockerhub send an event to keel's webhook 
- keel pull the image from Dockerhub and update it on Kubernetes
- keel send a notification on slack so that the developer knows his or her changes are ready to be previewed

Step:
- Configure testing env to mirror all production services ( Kubernetes )
- Configure CI
- Configure Keel
- Push a sample image to Docker Hub
- Configure Webhook on Dockerhub
- Test the changes.

**Comment by rohithbalaji123** [comment]
Finished creating testing environment for short, kgs and status page along with @byliuyang .
