### ISSUE TITLE
[Feature] Manage access control through authorizer

### ISSUE THREAD

**Issue by byliuyang** [short-d/short#729]
**What is the problem?**
Currently, there is no way to restrict an user from accessing protected resources, such as updating the change log, disable malicious user account, disable malicious short link, edit short links, view Analytics, or manage user roles.

**Your solution**
Create authorizer to manage user roles and permissions. For permission modal, we use RBAC: role-based access control.

**Additional context**
https://short-d.com/r/security
Sample code: https://github.com/short-d/short/tree/permission

**Comment by byliuyang** [comment]
Here are some hints:

1) Discuss user roles DB table design under this issue.
1) Implement `UserRole` repository with DB integration tests.
1) Create `authoriztor` with only `CanCreateChange` for now ( unit tests included ).
1) Update [CreateChange](https://github.com/short-d/short/blob/master/backend/app/usecase/changelog/changelog.go#L29) interface and integrate it with `authorizer`.
1) Update `createChange` GraphQL resolver.
1) Discuss features and their related permissions under this issue.
1) Add the rest of permission checker to Create `authoriztor`.

**Comment by alldroll** [comment]
# DB storage schema proposal

Roles model tends to be high read, as there are a lot of cases when the knowledge about the user's permission is required. It means, that the proposed DB schema should satisfy the described requirements of efficiency and be space-efficient as well.

A user can have several roles at the time, so I would like to consider several designs approaches

## Roles as a bitmasks

A role entity can be represented as a bitmask. Let's consider the cons and pros.

### Pros and Cons

**Pros**
* Space efficiency (we are going to store `uint64` for all user's roles)
* One to one relation model
* No duplication rows

**Cons**
* The limited list of roles. We can store bitmasks as `uint64`, which give as the restricted list of roles that can be created.
* Logic with bitmasks manipulation (but it can easily provide a declarative way to work with them) 

### Table schema

```SQL

CREATE TABLE "user_role"
(
    "user_id"              CHARACTER VARYING(5) PRIMARY KEY, -- OR UNIQUE KEY
    "roles"                BIT VARYING(64) NOT NULL,
     -- optional columns like created_at, updated_at
    FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE
);

```

### Entities

```go

type Role uint64

const (
   Basic Role = 1 << 0
   SecuritySpecialist = 1 << 1
   ...
   Admin = 1 << 63
)

// Roles set can be represented as uint64 or []Role

```


## One-to-many model

A user role is going to be a separate row in DB.

### Pros and Cons

**Pros**
* Simple and intuitive logic
* No limit on the number of roles

**Cons**
* Space inefficiency
* Unique constraints on roles. We have to create `unique_key (user_id, role)` in order to avoid duplicates.


### Table schema


```SQL

CREATE TABLE "user_role"
(
    "user_id"             CHARACTER VARYING(5) NOT NULL,
    "role"                CHARACTER VARYING(254) NOT NULL,
    -- optional columns like created_at, updated_at
    CONSTRAINT pk_user_role_relation PRIMARY KEY (user_id, role),
    FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE
);

```

**Comment by byliuyang** [comment]
I like `One-to-many model` because it provide DB admin readability. I recommend using `basic`, `security_specialist`, `admin`.

**Comment by byliuyang** [comment]
The bitwise operations are cool ideas though!
