### ISSUE TITLE
[Refactor] Change ReCaptcha API body to a map

### ISSUE THREAD

**Issue by byliuyang** [short-d/short#739]
**What is frustrating you?**
With manually concatenated string, it's error prone to add new query parameter to reCaptcha.

**Your solution**
Change the manually concatenated string to a map.

**Comment by Coteh** [comment]
After some quick digging, seems like the `siteverify` endpoint only accepts `application/x-www-form-urlencoded` input. Meaning that a concatenated url-encoded string should be generated by iterating through the keys of the map.

I can take this task. I am not sure if a helper method that does something like I suggested already exists. If it does, then I'll use that. Otherwise I can do it within the `Verify` function itself (shouldn't be too complex) and if we need it for other things it can be extracted out later.

**Comment by byliuyang** [comment]
@Coteh Thanks!
